//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeytiaServiceBL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiccVarConf {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiccVarConf() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeytiaServiceBL.DiccVarConf", typeof(DiccVarConf).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SELECT MAX(iCodRegistro) + 1 FROM {0}),.
        /// </summary>
        internal static string CalcularID {
            get {
                return ResourceManager.GetString("CalcularID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dtfecultact.
        /// </summary>
        internal static string CampodtUltFecAct {
            get {
                return ResourceManager.GetString("CampodtUltFecAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icodcatalogo.
        /// </summary>
        internal static string CampoiCodCatalogo {
            get {
                return ResourceManager.GetString("CampoiCodCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icodregistro.
        /// </summary>
        internal static string CampoiCodRegistro {
            get {
                return ResourceManager.GetString("CampoiCodRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (iCodRegistro, iCodCatalogo, vchCodigo, dtIniVigencia, dtFinVigencia, vchDescripcion, dtFecUltAct).
        /// </summary>
        internal static string CamposCatInsertHist {
            get {
                return ResourceManager.GetString("CamposCatInsertHist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Cargas&apos;,&apos;Cargas Factura Telcel&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string CargaFacturaTelcel {
            get {
                return ResourceManager.GetString("CargaFacturaTelcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conexionCollaborationKeytiaManagement.
        /// </summary>
        internal static string ConexionCollaborationKeytiaManagement {
            get {
                return ResourceManager.GetString("ConexionCollaborationKeytiaManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conexionCollaborationKMKeytiaManagement.
        /// </summary>
        internal static string ConexionCollaborationKMKeytiaManagement {
            get {
                return ResourceManager.GetString("ConexionCollaborationKMKeytiaManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConexionDefault.
        /// </summary>
        internal static string ConexionDefault {
            get {
                return ResourceManager.GetString("ConexionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conexion157.
        /// </summary>
        internal static string ConexionKeytia5_157 {
            get {
                return ResourceManager.GetString("ConexionKeytia5_157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conexion159.
        /// </summary>
        internal static string ConexionKeytia5_159 {
            get {
                return ResourceManager.GetString("ConexionKeytia5_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conexionCollaboration.
        /// </summary>
        internal static string ConexionKeytia5_Collaboration {
            get {
                return ResourceManager.GetString("ConexionKeytia5_Collaboration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conexion157KeytiaManagement.
        /// </summary>
        internal static string ConexionKeytiaManagement_157 {
            get {
                return ResourceManager.GetString("ConexionKeytiaManagement_157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conexion159KeytiaManagement.
        /// </summary>
        internal static string ConexionKeytiaManagement_159 {
            get {
                return ResourceManager.GetString("ConexionKeytiaManagement_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conexion159KMKeytiaManagement.
        /// </summary>
        internal static string ConexionKMKeytiaManagement_159 {
            get {
                return ResourceManager.GetString("ConexionKMKeytiaManagement_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conexion159Siana.
        /// </summary>
        internal static string ConexionSiana_159 {
            get {
                return ResourceManager.GetString("ConexionSiana_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE.
        /// </summary>
        internal static string DataBase {
            get {
                return ResourceManager.GetString("DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/UserInterface/DashboardFC/Dashboard.aspx.
        /// </summary>
        internal static string DefaultHomePageEmple {
            get {
                return ResourceManager.GetString("DefaultHomePageEmple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/UserInterface/DashboardFC/DashboardConsumoIndiv.aspx.
        /// </summary>
        internal static string DefaultHomePageEmpleBAT {
            get {
                return ResourceManager.GetString("DefaultHomePageEmpleBAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisDetallados(&apos;Detall&apos;,&apos;Detalle Centro de Costos&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string DetalladoCargaCentrosCostos {
            get {
                return ResourceManager.GetString("DetalladoCargaCentrosCostos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisDetallados(&apos;Detall&apos;,&apos;Detalle Codigo Autorizacion&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string DetalladoCargaCodigosAuto {
            get {
                return ResourceManager.GetString("DetalladoCargaCodigosAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisDetallados(&apos;Detall&apos;,&apos;Detalle Empleados&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string DetalladoCargaEmpleados {
            get {
                return ResourceManager.GetString("DetalladoCargaEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisDetallados(&apos;Detall&apos;,&apos;Detalle Extensiones&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string DetalladoCargaExtensiones {
            get {
                return ResourceManager.GetString("DetalladoCargaExtensiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisDetallados(&apos;Detall&apos;,&apos;Detalle Lineas&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string DetalladoCargaLineas {
            get {
                return ResourceManager.GetString("DetalladoCargaLineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisDetallados(&apos;Detall&apos;,&apos;Detalle Usuarios&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string DetalladoCargaUsuarios {
            get {
                return ResourceManager.GetString("DetalladoCargaUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisDetallados(&apos;Detall&apos;,&apos;Detallado Usuarios&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string DetalladoUsuariosKeytia {
            get {
                return ResourceManager.GetString("DetalladoUsuariosKeytia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectorioCargas.
        /// </summary>
        internal static string DirCargasKey {
            get {
                return ResourceManager.GetString("DirCargasKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectorioLogoClientes.
        /// </summary>
        internal static string DirLogoClientesKey {
            get {
                return ResourceManager.GetString("DirLogoClientesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2079-01-01 00:00:00.
        /// </summary>
        internal static string FechaDefaultMax {
            get {
                return ResourceManager.GetString("FechaDefaultMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011-01-01 00:00:00.
        /// </summary>
        internal static string FechaDefaultMin {
            get {
                return ResourceManager.GetString("FechaDefaultMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}], .
        /// </summary>
        internal static string FormatCampoInsert {
            get {
                return ResourceManager.GetString("FormatCampoInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [{0}] = {1}.
        /// </summary>
        internal static string FormatCampoUpDate {
            get {
                return ResourceManager.GetString("FormatCampoUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uid={0};pwd={1};.
        /// </summary>
        internal static string FormatoCadenaCliente {
            get {
                return ResourceManager.GetString("FormatoCadenaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.
        /// </summary>
        internal static string FormatoFecha {
            get {
                return ResourceManager.GetString("FormatoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &apos;{0}&apos;,.
        /// </summary>
        internal static string FormatoVarChar {
            get {
                return ResourceManager.GetString("FormatoVarChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SELECT iCodRegistro FROM @iCodRegCat),.
        /// </summary>
        internal static string GetIdCat {
            get {
                return ResourceManager.GetString("GetIdCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Cargas&apos;,&apos;Cargas Empleado&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoCargasEmpleado {
            get {
                return ResourceManager.GetString("HistoricoCargasEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Cargas&apos;,&apos;Cargas Factura Movistar&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoCargasFacturaMovistar {
            get {
                return ResourceManager.GetString("HistoricoCargasFacturaMovistar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Cencos&apos;,&apos;Centro de Costos&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoCentroDeCosto {
            get {
                return ResourceManager.GetString("HistoricoCentroDeCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;CodAuto&apos;,&apos;Codigo Autorizacion&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoCodigosAuto {
            get {
                return ResourceManager.GetString("HistoricoCodigosAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;CtaMaestra&apos;,&apos;Cuenta Maestra Carrier&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoCuentaMaestraCarrier {
            get {
                return ResourceManager.GetString("HistoricoCuentaMaestraCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Emple&apos;,&apos;Empleados&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoEmpleado {
            get {
                return ResourceManager.GetString("HistoricoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;EqCelular&apos;,&apos;Equipo Celular&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoEquipoCelular {
            get {
                return ResourceManager.GetString("HistoricoEquipoCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Estados&apos;,&apos;Estados&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoEstados {
            get {
                return ResourceManager.GetString("HistoricoEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;EstCarga&apos;,&apos;Estatus Cargas&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoEstatusCarga {
            get {
                return ResourceManager.GetString("HistoricoEstatusCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Exten&apos;,&apos;Extensiones&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoExtension {
            get {
                return ResourceManager.GetString("HistoricoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Idioma&apos;,&apos;Idioma&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoIdioma {
            get {
                return ResourceManager.GetString("HistoricoIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Linea&apos;,&apos;Lineas&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoLinea {
            get {
                return ResourceManager.GetString("HistoricoLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Locali&apos;,&apos;Localidades&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoLocali {
            get {
                return ResourceManager.GetString("HistoricoLocali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Moneda&apos;,&apos;Monedas&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoMoneda {
            get {
                return ResourceManager.GetString("HistoricoMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Organizacion&apos;,&apos;Organizacion&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoOrganizacion {
            get {
                return ResourceManager.GetString("HistoricoOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Paises&apos;,&apos;Paises&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoPaises {
            get {
                return ResourceManager.GetString("HistoricoPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Perfil&apos;,&apos;Perfiles&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoPerfiles {
            get {
                return ResourceManager.GetString("HistoricoPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;PlanTarif&apos;,&apos;Plan Tarifario&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoPlanTarifario {
            get {
                return ResourceManager.GetString("HistoricoPlanTarifario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Puesto&apos;,&apos;Puestos Empleado&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoPuestoEmpleado {
            get {
                return ResourceManager.GetString("HistoricoPuestoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;RazonSocial&apos;,&apos;Razon Social&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoRazonSocial {
            get {
                return ResourceManager.GetString("HistoricoRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;SitioTIM&apos;,&apos;Sitios TIM&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoSitioTIM {
            get {
                return ResourceManager.GetString("HistoricoSitioTIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;SitioTIMNombrePublico&apos;,&apos;Sitios TIM Nombre Publico&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoSitioTIMNombrePublico {
            get {
                return ResourceManager.GetString("HistoricoSitioTIMNombrePublico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;UsuarDB&apos;,&apos;Usuarios DB&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricosUsuariosDB {
            get {
                return ResourceManager.GetString("HistoricosUsuariosDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;TDest&apos;,&apos;Tipo de Destino&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoTDest {
            get {
                return ResourceManager.GetString("HistoricoTDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;TipoEm&apos;,&apos;Tipo Empleado&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoTipoEmpleado {
            get {
                return ResourceManager.GetString("HistoricoTipoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;TipoLicenciaExtension&apos;,&apos;Tipo de Licencia para Extension&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoTipoLicenciaExtension {
            get {
                return ResourceManager.GetString("HistoricoTipoLicenciaExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;TipoPlan&apos;,&apos;Tipo Plan&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoTipoPlan {
            get {
                return ResourceManager.GetString("HistoricoTipoPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Usuar&apos;,&apos;Usuarios&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoUsuarios {
            get {
                return ResourceManager.GetString("HistoricoUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;UsuarDB&apos;,&apos;Usuarios DB&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string HistoricoUsuariosDB {
            get {
                return ResourceManager.GetString("HistoricoUsuariosDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO {0}.
        /// </summary>
        internal static string InstruccionInsert {
            get {
                return ResourceManager.GetString("InstruccionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT INSERTED.{0}.
        /// </summary>
        internal static string InstruccionOutPut {
            get {
                return ResourceManager.GetString("InstruccionOutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select {0} from @inserted.
        /// </summary>
        internal static string InstruccionSelectOUTPUT {
            get {
                return ResourceManager.GetString("InstruccionSelectOUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE {0}.
        /// </summary>
        internal static string InstruccionUpdate {
            get {
                return ResourceManager.GetString("InstruccionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeytiaManagement.
        /// </summary>
        internal static string KeytiaManagementBD {
            get {
                return ResourceManager.GetString("KeytiaManagementBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vishistorico.
        /// </summary>
        internal static string NombreGenericoHistorico {
            get {
                return ResourceManager.GetString("NombreGenericoHistorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visrelaciones.
        /// </summary>
        internal static string NombreGenericoRelaciones {
            get {
                return ResourceManager.GetString("NombreGenericoRelaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisPendientes(&apos;Detall&apos;,&apos;Centro de CostosPendiente&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string PendientesCargaCenCos {
            get {
                return ResourceManager.GetString("PendientesCargaCenCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisPendientes(&apos;Detall&apos;,&apos;Codigo AutorizacionPendiente&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string PendientesCargaCodigosAuto {
            get {
                return ResourceManager.GetString("PendientesCargaCodigosAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisPendientes(&apos;Detall&apos;,&apos;EmpleadosPendiente&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string PendientesCargaEmpleado {
            get {
                return ResourceManager.GetString("PendientesCargaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisPendientes(&apos;Detall&apos;,&apos;ExtensionesPendiente&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string PendientesCargaExtensiones {
            get {
                return ResourceManager.GetString("PendientesCargaExtensiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisPendientes(&apos;Detall&apos;,&apos;LineasPendiente&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string PendientesCargaLineas {
            get {
                return ResourceManager.GetString("PendientesCargaLineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisPendientes(&apos;Detall&apos;,&apos;Usuarios Pendiente&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string PendientesCargaUsuarios {
            get {
                return ResourceManager.GetString("PendientesCargaUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\w+([-+.&apos;]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$.
        /// </summary>
        internal static string RegexValidarEmail {
            get {
                return ResourceManager.GetString("RegexValidarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaciones.
        /// </summary>
        internal static string Relacion {
            get {
                return ResourceManager.GetString("Relacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisRelaciones(&apos;CentroCosto-Empleado&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string RelacionCenCosEmple {
            get {
                return ResourceManager.GetString("RelacionCenCosEmple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisRelaciones(&apos;Empleado - CodAutorizacion&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string RelacionCodAutoEmple {
            get {
                return ResourceManager.GetString("RelacionCodAutoEmple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisRelaciones(&apos;Empleado - Extension&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string RelacionExtenEmple {
            get {
                return ResourceManager.GetString("RelacionExtenEmple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisRelaciones(&apos;Empleado - Linea&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string RelacionLineaEmple {
            get {
                return ResourceManager.GetString("RelacionLineaEmple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTIMTYKEYTIA02.
        /// </summary>
        internal static string ServerProduccion {
            get {
                return ResourceManager.GetString("ServerProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historicos.
        /// </summary>
        internal static string TablaHistorico {
            get {
                return ResourceManager.GetString("TablaHistorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarcacionLocalidades.
        /// </summary>
        internal static string TablaMarcacionLocalidades {
            get {
                return ResourceManager.GetString("TablaMarcacionLocalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaciones.
        /// </summary>
        internal static string TablaRelaciones {
            get {
                return ResourceManager.GetString("TablaRelaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TOP(1) [TIMInventarioRecursos] SET FechaBajaInt = {0}, Estatus = &apos;INACTIVO&apos;, dtFecUltAct = GETDATE(), UltFecFacAct = {1} WHERE LadaTelefono = &apos;{2}&apos; AND iCodCatClaveCar = {3} AND Estatus = &apos;ACTIVO&apos; AND iCodCatCarrier = {4} AND iCodCatRecursoContratado = {5} AND Cantidad = {6} AND iCodCatEmpre = {7};.
        /// </summary>
        internal static string TIMInventarioQueryBaja {
            get {
                return ResourceManager.GetString("TIMInventarioQueryBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TOP(1) [TIMInventarioRecursos] SET FechaBajaInt = NULL, FechaAltaInt = {0}, Estatus = &apos;ACTIVO&apos;, dtFecUltAct = GETDATE(), UltFecFacAct = {1} WHERE LadaTelefono = &apos;{2}&apos; AND iCodCatClaveCar = {3} AND Estatus = &apos;INACTIVO&apos; AND iCodCatCarrier = {4} AND iCodCatRecursoContratado = {5} AND Cantidad = {6} AND iCodCatEmpre = {7};.
        /// </summary>
        internal static string TIMInventarioQueryBajaToAlta {
            get {
                return ResourceManager.GetString("TIMInventarioQueryBajaToAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TOP(1) [TIMInventarioRecursos] SET Cuenta = &apos;{0}&apos;, Subcuenta = &apos;{1}&apos;, dtFecUltAct = GETDATE(), UltFecFacAct = {2} WHERE LadaTelefono = &apos;{3}&apos; AND iCodCatClaveCar = {4} AND iCodCatCarrier = {5} AND iCodCatRecursoContratado = {6}  AND iCodCatEmpre = {7};.
        /// </summary>
        internal static string TIMInventarioQueryUpdateCtaSubCuenta {
            get {
                return ResourceManager.GetString("TIMInventarioQueryUpdateCtaSubCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TOP(1) [TIMInventarioRecursos] SET iCodUbicaRecur = {0}, dtFecUltAct = GETDATE() WHERE LadaTelefono = &apos;{1}&apos; AND iCodCatCarrier = {2} AND iCodCatEmpre = {3};.
        /// </summary>
        internal static string TIMInventarioQueryUpdateUbicaRecurs {
            get {
                return ResourceManager.GetString("TIMInventarioQueryUpdateUbicaRecurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMAlestraDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMAlestraDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMAlestraDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMATTDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMATTDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMATTDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMAxtelCargosUnicos.
        /// </summary>
        internal static string TIMTablaTIMAxtelCargosUnicos {
            get {
                return ResourceManager.GetString("TIMTablaTIMAxtelCargosUnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMAxtelDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMAxtelDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMAxtelDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMAxtelv2DetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMAxtelv2DetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMAxtelv2DetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMBBSDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMBBSDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMBBSDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMBestelDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMBestelDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMBestelDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMBTDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMBTDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMBTDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMComIntCelDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMComIntCelDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMComIntCelDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMConceptoMovilDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMConceptoMovilDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMConceptoMovilDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMConsolidadoPorClaveCargo.
        /// </summary>
        internal static string TIMTablaTIMConsolidadoPorClaveCargo {
            get {
                return ResourceManager.GetString("TIMTablaTIMConsolidadoPorClaveCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMConsolidadoPorSitio.
        /// </summary>
        internal static string TIMTablaTIMConsolidadoPorSitio {
            get {
                return ResourceManager.GetString("TIMTablaTIMConsolidadoPorSitio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMCreativeNetDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMCreativeNetDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMCreativeNetDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMCreatividadInternetDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMCreatividadInternetDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMCreatividadInternetDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMDSCDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMDSCDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMDSCDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMFacturaXML.
        /// </summary>
        internal static string TIMTablaTIMFacturaXML {
            get {
                return ResourceManager.GetString("TIMTablaTIMFacturaXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMFive9DetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMFive9DetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMFive9DetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMGlobalcomsysDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMGlobalcomsysDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMGlobalcomsysDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMGlobalSatDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMGlobalSatDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMGlobalSatDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMGlobalSatV2DetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMGlobalSatV2DetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMGlobalSatV2DetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMHO1ADetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMHO1ADetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMHO1ADetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMInventarioRecursos.
        /// </summary>
        internal static string TIMTablaTIMInventarioRecursos {
            get {
                return ResourceManager.GetString("TIMTablaTIMInventarioRecursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMITTMichDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMITTMICHDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMITTMICHDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMIusacellDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMIusacellDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMIusacellDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMKonectaDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMKonectaDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMKonectaDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMKonectaDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMKonetaDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMKonetaDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMMarcatelDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMMarcatelDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMMarcatelDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMMaxcomGenericoDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMMaxcomGenericoDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMMaxcomGenericoDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMMegaCableDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMMegaCableDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMMegaCableDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMMETROCARRIERDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMMETROCARRIERDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMMETROCARRIERDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMMovistarDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMMovistarDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMMovistarDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMNetLinkDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMNetLinkDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMNetLinkDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMPODERNETDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMPODERNETDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMPODERNETDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMReactivacionesInventarioRecur.
        /// </summary>
        internal static string TIMTablaTIMReactivacionesInventarioRecur {
            get {
                return ResourceManager.GetString("TIMTablaTIMReactivacionesInventarioRecur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMRentaGlobal.
        /// </summary>
        internal static string TIMTablaTIMRentaGlobal {
            get {
                return ResourceManager.GetString("TIMTablaTIMRentaGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMRentaPorSubCuenta.
        /// </summary>
        internal static string TIMTablaTIMRentaPorSubCuenta {
            get {
                return ResourceManager.GetString("TIMTablaTIMRentaPorSubCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMSariaDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMSariaDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMSariaDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMSIERRAMADREDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMSIERRAMADREDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMSIERRAMADREDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMSmartNettDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMSmartNettDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMSmartNettDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMSoftelDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMSoftelDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMSoftelDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMTarifaGlobal.
        /// </summary>
        internal static string TIMTablaTIMTarifaGlobal {
            get {
                return ResourceManager.GetString("TIMTablaTIMTarifaGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMTarifaPorSubCuenta.
        /// </summary>
        internal static string TIMTablaTIMTarifaPorSubCuenta {
            get {
                return ResourceManager.GetString("TIMTablaTIMTarifaPorSubCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMTelefonicaDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMTelefonicaDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMTelefonicaDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMTelmexUninetFullDetalle.
        /// </summary>
        internal static string TIMTablaTIMTelmexUninetFullDetalle {
            get {
                return ResourceManager.GetString("TIMTablaTIMTelmexUninetFullDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMTelumDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMTelumDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMTelumDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMTotalPlayDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMTotalPlayDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMTotalPlayDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMTranstelcoDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMTranstelcoDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMTranstelcoDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMUBIXDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMUBIXDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMUBIXDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMWICODetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMWICODetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMWICODetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMXpertusDetalleFactura.
        /// </summary>
        internal static string TIMTablaTIMXpertusDetalleFactura {
            get {
                return ResourceManager.GetString("TIMTablaTIMXpertusDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string TipoDateTime {
            get {
                return ResourceManager.GetString("TipoDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string TipoString {
            get {
                return ResourceManager.GetString("TipoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        internal static string TopDeValoresAEliminarBD {
            get {
                return ResourceManager.GetString("TopDeValoresAEliminarBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER ID.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string ValorEntidadEmpleado {
            get {
                return ResourceManager.GetString("ValorEntidadEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VisHistoricos(&apos;Valores&apos;,&apos;Valores&apos;,&apos;Español&apos;)].
        /// </summary>
        internal static string Valores {
            get {
                return ResourceManager.GetString("Valores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  NULL,.
        /// </summary>
        internal static string ValorNull {
            get {
                return ResourceManager.GetString("ValorNull", resourceCulture);
            }
        }
    }
}
