//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeytiaServiceBL {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiccMens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiccMens() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeytiaServiceBL.DiccMens", typeof(DiccMens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base de datos no disponible..
        /// </summary>
        internal static string DA001 {
            get {
                return ResourceManager.GetString("DA001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error en la capa de AccessLayer.
        /// </summary>
        internal static string DA002 {
            get {
                return ResourceManager.GetString("DA002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere el Id de la entidad del elemento..
        /// </summary>
        internal static string DA003 {
            get {
                return ResourceManager.GetString("DA003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error en la capa de Datos..
        /// </summary>
        internal static string DL001 {
            get {
                return ResourceManager.GetString("DL001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en los datos.
        /// </summary>
        internal static string DL002 {
            get {
                return ResourceManager.GetString("DL002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Código ya existe: {0}.
        /// </summary>
        internal static string DL003 {
            get {
                return ResourceManager.GetString("DL003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Extensión ya existe: {0}.
        /// </summary>
        internal static string DL004 {
            get {
                return ResourceManager.GetString("DL004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Empleado ya existe: {0}.
        /// </summary>
        internal static string DL005 {
            get {
                return ResourceManager.GetString("DL005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Linea ya existe: {0}.
        /// </summary>
        internal static string DL006 {
            get {
                return ResourceManager.GetString("DL006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario ya existe: {0}.
        /// </summary>
        internal static string DL007 {
            get {
                return ResourceManager.GetString("DL007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por seguridad no se permite un borrado logico del historico si este tiene relaciones activas o historia..
        /// </summary>
        internal static string DL008 {
            get {
                return ResourceManager.GetString("DL008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fechas Invalidas o no se encontró el elemento..
        /// </summary>
        internal static string DL009 {
            get {
                return ResourceManager.GetString("DL009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay traslape de fechas.
        /// </summary>
        internal static string DL010 {
            get {
                return ResourceManager.GetString("DL010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible dar de baja la relación actualmente activa. Las fechas no van de forma cronologica. La fecha de inicio de esta relacion es menor a la fecha de inicio de la relación actualmente activa..
        /// </summary>
        internal static string DL011 {
            get {
                return ResourceManager.GetString("DL011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se encontró más de una relación activa..
        /// </summary>
        internal static string DL012 {
            get {
                return ResourceManager.GetString("DL012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el historico..
        /// </summary>
        internal static string DL013 {
            get {
                return ResourceManager.GetString("DL013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fechas no validas..
        /// </summary>
        internal static string DL014 {
            get {
                return ResourceManager.GetString("DL014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el centro de costos por indentificar..
        /// </summary>
        internal static string DL015 {
            get {
                return ResourceManager.GetString("DL015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede dar de baja el elemento. Cuenta con relaciones activas..
        /// </summary>
        internal static string DL016 {
            get {
                return ResourceManager.GetString("DL016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos del Empleado son incorrectos favor de validar..
        /// </summary>
        internal static string DL017 {
            get {
                return ResourceManager.GetString("DL017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible reactivar el empleado. El último centro de costos al que pertenció no esta  activo..
        /// </summary>
        internal static string DL018 {
            get {
                return ResourceManager.GetString("DL018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear el empleado. Las fechas ingresadas coinciden con las de otro registro..
        /// </summary>
        internal static string DL019 {
            get {
                return ResourceManager.GetString("DL019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El centro de costos con el que se desea relacionar al empleado no exixte o no se encuentra activo..
        /// </summary>
        internal static string DL020 {
            get {
                return ResourceManager.GetString("DL020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos de la extensión son incorrectos favor de validar..
        /// </summary>
        internal static string DL021 {
            get {
                return ResourceManager.GetString("DL021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos del código de autorización son incorrectos favor de validar..
        /// </summary>
        internal static string DL022 {
            get {
                return ResourceManager.GetString("DL022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos de la línea son incorrectos favor de validar..
        /// </summary>
        internal static string DL023 {
            get {
                return ResourceManager.GetString("DL023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos del usuario son incorrectos favor de validar..
        /// </summary>
        internal static string DL024 {
            get {
                return ResourceManager.GetString("DL024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La nómina ingresada no es válida..
        /// </summary>
        internal static string DL025 {
            get {
                return ResourceManager.GetString("DL025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible dar de baja la relación de centro de costos: La Fecha Inicio no puede ser mayor a la Fecha Fin..
        /// </summary>
        internal static string DL026 {
            get {
                return ResourceManager.GetString("DL026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El sitio no se encuentra activo..
        /// </summary>
        internal static string DL027 {
            get {
                return ResourceManager.GetString("DL027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El empleado no se encuentra activo..
        /// </summary>
        internal static string DL028 {
            get {
                return ResourceManager.GetString("DL028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear la extension. Las fechas coinciden con las de otro registro..
        /// </summary>
        internal static string DL029 {
            get {
                return ResourceManager.GetString("DL029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el historico para actualizar el atributo..
        /// </summary>
        internal static string DL030 {
            get {
                return ResourceManager.GetString("DL030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se podra dar de baja una relacion con una Fecha Fin posterior a la Fecha Fin que tiene actualmente..
        /// </summary>
        internal static string DL031 {
            get {
                return ResourceManager.GetString("DL031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el empleado &quot;POR IDENTIFICAR&quot;. para actualizar el atributo..
        /// </summary>
        internal static string DL032 {
            get {
                return ResourceManager.GetString("DL032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró ninguna relación anterior de Centro de costos al cual asignar el empleado. Inconsistencia. Empleado sin CenCos, Nómina:  {0}.
        /// </summary>
        internal static string DL033 {
            get {
                return ResourceManager.GetString("DL033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rango de la relación esta fuera de los rangos de Empleado. El rango del empleado es: {0} - {1}.
        /// </summary>
        internal static string DL034 {
            get {
                return ResourceManager.GetString("DL034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear la relación. Hay traslape de fechas entre las relaciones de la misma extensión con las que cuenta el empleado..
        /// </summary>
        internal static string DL035 {
            get {
                return ResourceManager.GetString("DL035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear el código de autorización. Las fechas coinciden con las de otro registro..
        /// </summary>
        internal static string DL036 {
            get {
                return ResourceManager.GetString("DL036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Carrier no se encuentra activo..
        /// </summary>
        internal static string DL038 {
            get {
                return ResourceManager.GetString("DL038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear la linea. Las fechas coinciden con las de otro registro..
        /// </summary>
        internal static string DL039 {
            get {
                return ResourceManager.GetString("DL039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en las fechas. Sale de los rangos de vigencia de los registros del Empleado..
        /// </summary>
        internal static string DL040 {
            get {
                return ResourceManager.GetString("DL040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el historico del Usuario..
        /// </summary>
        internal static string DL041 {
            get {
                return ResourceManager.GetString("DL041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se fue posible dar de alta la extension por que esta fuera del rango del sitio..
        /// </summary>
        internal static string DL042 {
            get {
                return ResourceManager.GetString("DL042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible eliminar el registro de Detallados..
        /// </summary>
        internal static string DL043 {
            get {
                return ResourceManager.GetString("DL043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible eliminar el registro de Pendientes..
        /// </summary>
        internal static string DL044 {
            get {
                return ResourceManager.GetString("DL044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario o Email ya existen..
        /// </summary>
        internal static string DL045 {
            get {
                return ResourceManager.GetString("DL045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No contiene todos los campos requeridos..
        /// </summary>
        internal static string DL046 {
            get {
                return ResourceManager.GetString("DL046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Email ya existe..
        /// </summary>
        internal static string DL047 {
            get {
                return ResourceManager.GetString("DL047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe la combinación de usuario y password..
        /// </summary>
        internal static string DL048 {
            get {
                return ResourceManager.GetString("DL048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el formato del e-mail..
        /// </summary>
        internal static string DL049 {
            get {
                return ResourceManager.GetString("DL049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base de datos no disponible..
        /// </summary>
        internal static string DL050 {
            get {
                return ResourceManager.GetString("DL050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear la relación. Hay traslape de fechas entre las relaciones del mismo código con las que cuenta el empleado..
        /// </summary>
        internal static string DL051 {
            get {
                return ResourceManager.GetString("DL051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos del puesto son incorrectos favor de validar..
        /// </summary>
        internal static string DL052 {
            get {
                return ResourceManager.GetString("DL052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Puesto ya existe..
        /// </summary>
        internal static string DL053 {
            get {
                return ResourceManager.GetString("DL053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear el puesto. Las fechas coinciden con las de otro registro..
        /// </summary>
        internal static string DL054 {
            get {
                return ResourceManager.GetString("DL054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró puedo identificar un tipo de Recurso para el carrier de la Linea..
        /// </summary>
        internal static string DL055 {
            get {
                return ResourceManager.GetString("DL055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos del Sitio TIM son incorrectos..
        /// </summary>
        internal static string DL056 {
            get {
                return ResourceManager.GetString("DL056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Sitio TIM ya existe..
        /// </summary>
        internal static string DL057 {
            get {
                return ResourceManager.GetString("DL057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear el Sitio TIM, las fechs coinciden con las de otro registro..
        /// </summary>
        internal static string DL058 {
            get {
                return ResourceManager.GetString("DL058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos de {0} son incorrectos, favor de validar..
        /// </summary>
        internal static string DL059 {
            get {
                return ResourceManager.GetString("DL059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Ya existe {0}].
        /// </summary>
        internal static string DL060 {
            get {
                return ResourceManager.GetString("DL060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [No fue posible crear {0}. Las fechas coinciden con las de otro registro.].
        /// </summary>
        internal static string DL061 {
            get {
                return ResourceManager.GetString("DL061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Los datos de {0} son incorrectos, favor de validar.].
        /// </summary>
        internal static string DL062 {
            get {
                return ResourceManager.GetString("DL062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extensión privada.
        /// </summary>
        internal static string ExtensionPrivada {
            get {
                return ResourceManager.GetString("ExtensionPrivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error en la capa de Logic.
        /// </summary>
        internal static string LL001 {
            get {
                return ResourceManager.GetString("LL001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo realizar la acción..
        /// </summary>
        internal static string LL002 {
            get {
                return ResourceManager.GetString("LL002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos no válidos en el campo {0}..
        /// </summary>
        internal static string LL003 {
            get {
                return ResourceManager.GetString("LL003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La creación del nuevo cliente falló..
        /// </summary>
        internal static string LL004 {
            get {
                return ResourceManager.GetString("LL004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia Creación de Cliente..
        /// </summary>
        internal static string LL005 {
            get {
                return ResourceManager.GetString("LL005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario y/o Password son incorrectos..
        /// </summary>
        internal static string LL006 {
            get {
                return ResourceManager.GetString("LL006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento duplicado..
        /// </summary>
        internal static string LL007 {
            get {
                return ResourceManager.GetString("LL007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error en la lectura del archivo Excel..
        /// </summary>
        internal static string LL008 {
            get {
                return ResourceManager.GetString("LL008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible. Categoría y/o Perfil Desactivados..
        /// </summary>
        internal static string LL009 {
            get {
                return ResourceManager.GetString("LL009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        internal static string LL010 {
            get {
                return ResourceManager.GetString("LL010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron presupuestos activos..
        /// </summary>
        internal static string LL011 {
            get {
                return ResourceManager.GetString("LL011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró información en la hoja RH o Cod_Ext. La información en estas hojas es obligatoria..
        /// </summary>
        internal static string LL012 {
            get {
                return ResourceManager.GetString("LL012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar crear el registro de la carga..
        /// </summary>
        internal static string LL013 {
            get {
                return ResourceManager.GetString("LL013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un registro en historicos..
        /// </summary>
        internal static string LL014 {
            get {
                return ResourceManager.GetString("LL014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso no puede continuar. Hay Sitios en el archivo que no estan en el sistema..
        /// </summary>
        internal static string LL015 {
            get {
                return ResourceManager.GetString("LL015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un cliente con ese nombre de esquema en la base de datos..
        /// </summary>
        internal static string LL016 {
            get {
                return ResourceManager.GetString("LL016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación de cliente &quot;{0}&quot; {1}..
        /// </summary>
        internal static string LL017 {
            get {
                return ResourceManager.GetString("LL017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} proceso de creación de cliente &quot;{1}&quot;, Usuario: {2}..
        /// </summary>
        internal static string LL018 {
            get {
                return ResourceManager.GetString("LL018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear la carga..
        /// </summary>
        internal static string LL019 {
            get {
                return ResourceManager.GetString("LL019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere el nombre de la vista..
        /// </summary>
        internal static string LL020 {
            get {
                return ResourceManager.GetString("LL020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha creado una carga..
        /// </summary>
        internal static string LL021 {
            get {
                return ResourceManager.GetString("LL021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del Archivo no es valido..
        /// </summary>
        internal static string LL022 {
            get {
                return ResourceManager.GetString("LL022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el maestro..
        /// </summary>
        internal static string LL023 {
            get {
                return ResourceManager.GetString("LL023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La nómina ingresada ya existe. Nómina:{0}, Empleado: {1}.
        /// </summary>
        internal static string LL024 {
            get {
                return ResourceManager.GetString("LL024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear el Empleado..
        /// </summary>
        internal static string LL025 {
            get {
                return ResourceManager.GetString("LL025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear la Relación del Empleado con el Centro de Costos. Se creo una inconsistencia. Empleado sin CenCos, Nómina:  {0}.
        /// </summary>
        internal static string LL026 {
            get {
                return ResourceManager.GetString("LL026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear la extensión..
        /// </summary>
        internal static string LL027 {
            get {
                return ResourceManager.GetString("LL027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear la Relación de el Empleado con la Extensión..
        /// </summary>
        internal static string LL028 {
            get {
                return ResourceManager.GetString("LL028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha fin de la relación solo se puede actalizar hacia un fecha anterior..
        /// </summary>
        internal static string LL029 {
            get {
                return ResourceManager.GetString("LL029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible generar una nomina para el empleado..
        /// </summary>
        internal static string LL030 {
            get {
                return ResourceManager.GetString("LL030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear el código de autorización..
        /// </summary>
        internal static string LL031 {
            get {
                return ResourceManager.GetString("LL031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear la Relación del Empleado con el Código de Autorización.
        /// </summary>
        internal static string LL032 {
            get {
                return ResourceManager.GetString("LL032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear la Linea..
        /// </summary>
        internal static string LL033 {
            get {
                return ResourceManager.GetString("LL033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear la Relación del Empleado con la Linea.
        /// </summary>
        internal static string LL034 {
            get {
                return ResourceManager.GetString("LL034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible eliminar la relación del empleado con el centro de costos..
        /// </summary>
        internal static string LL035 {
            get {
                return ResourceManager.GetString("LL035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible eliminar la relación inmediata anterior del empleado con el centro de costos..
        /// </summary>
        internal static string LL036 {
            get {
                return ResourceManager.GetString("LL036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear el Usuario..
        /// </summary>
        internal static string LL037 {
            get {
                return ResourceManager.GetString("LL037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha Inicio no puede ser más grande que la Fecha Fin..
        /// </summary>
        internal static string LL038 {
            get {
                return ResourceManager.GetString("LL038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro no cuenta con todos los campos requeridos..
        /// </summary>
        internal static string LL039 {
            get {
                return ResourceManager.GetString("LL039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Centro de Costos no existe..
        /// </summary>
        internal static string LL040 {
            get {
                return ResourceManager.GetString("LL040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro duplicado en el archivo..
        /// </summary>
        internal static string LL041 {
            get {
                return ResourceManager.GetString("LL041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de empleado no existe..
        /// </summary>
        internal static string LL042 {
            get {
                return ResourceManager.GetString("LL042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el empleado para crear la relación con el CC: {0}.
        /// </summary>
        internal static string LL043 {
            get {
                return ResourceManager.GetString("LL043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La nómina del Jefe no existe..
        /// </summary>
        internal static string LL044 {
            get {
                return ResourceManager.GetString("LL044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro al empleado: {0}.
        /// </summary>
        internal static string LL045 {
            get {
                return ResourceManager.GetString("LL045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El empleado ya cuenta con un usuario..
        /// </summary>
        internal static string LL046 {
            get {
                return ResourceManager.GetString("LL046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro no contiene información para el username.
        /// </summary>
        internal static string LL047 {
            get {
                return ResourceManager.GetString("LL047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave de la carga es demasiado larga: {0}..
        /// </summary>
        internal static string LL048 {
            get {
                return ResourceManager.GetString("LL048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro el usuario..
        /// </summary>
        internal static string LL049 {
            get {
                return ResourceManager.GetString("LL049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entrada en la columna de CrearUsuario no es valida..
        /// </summary>
        internal static string LL050 {
            get {
                return ResourceManager.GetString("LL050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Sitio no existe..
        /// </summary>
        internal static string LL051 {
            get {
                return ResourceManager.GetString("LL051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Cos no existe..
        /// </summary>
        internal static string LL052 {
            get {
                return ResourceManager.GetString("LL052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el empleado para crear la relación con el Código..
        /// </summary>
        internal static string LL053 {
            get {
                return ResourceManager.GetString("LL053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el código de autorización: {0}.
        /// </summary>
        internal static string LL054 {
            get {
                return ResourceManager.GetString("LL054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Código de Autorización ya existe..
        /// </summary>
        internal static string LL055 {
            get {
                return ResourceManager.GetString("LL055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertando registro de carga....
        /// </summary>
        internal static string LL056 {
            get {
                return ResourceManager.GetString("LL056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vaciando datos del archivo....
        /// </summary>
        internal static string LL057 {
            get {
                return ResourceManager.GetString("LL057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando campos requeridos....
        /// </summary>
        internal static string LL058 {
            get {
                return ResourceManager.GetString("LL058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando y descartando nóminas sin Centro de Costos....
        /// </summary>
        internal static string LL059 {
            get {
                return ResourceManager.GetString("LL059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando y descartando nóminas duplicadas en el archivo....
        /// </summary>
        internal static string LL060 {
            get {
                return ResourceManager.GetString("LL060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Separando nóminas nuevas y nóminas que ya existen en base de datos....
        /// </summary>
        internal static string LL061 {
            get {
                return ResourceManager.GetString("LL061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando registros nuevos....
        /// </summary>
        internal static string LL062 {
            get {
                return ResourceManager.GetString("LL062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando registros existentes....
        /// </summary>
        internal static string LL063 {
            get {
                return ResourceManager.GetString("LL063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignando jefes....
        /// </summary>
        internal static string LL064 {
            get {
                return ResourceManager.GetString("LL064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga Finalizada..
        /// </summary>
        internal static string LL065 {
            get {
                return ResourceManager.GetString("LL065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en parametros de carga..
        /// </summary>
        internal static string LL066 {
            get {
                return ResourceManager.GetString("LL066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando y descartando códigos sin Sitio....
        /// </summary>
        internal static string LL067 {
            get {
                return ResourceManager.GetString("LL067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando y descartando códigos duplicados en el archivo....
        /// </summary>
        internal static string LL068 {
            get {
                return ResourceManager.GetString("LL068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Separando códigos nuevos y códigos que ya existen en base de datos....
        /// </summary>
        internal static string LL069 {
            get {
                return ResourceManager.GetString("LL069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando y descartando extensiones sin Sitio....
        /// </summary>
        internal static string LL070 {
            get {
                return ResourceManager.GetString("LL070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando y descartando extensiones duplicadas en el archivo....
        /// </summary>
        internal static string LL071 {
            get {
                return ResourceManager.GetString("LL071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Separando extensiones nuevas y extensiones que ya existen en base de datos....
        /// </summary>
        internal static string LL072 {
            get {
                return ResourceManager.GetString("LL072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el empleado para crear la relación con la extensión..
        /// </summary>
        internal static string LL073 {
            get {
                return ResourceManager.GetString("LL073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Extensión ya existe..
        /// </summary>
        internal static string LL074 {
            get {
                return ResourceManager.GetString("LL074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible restablecer todos los detallados..
        /// </summary>
        internal static string LL075 {
            get {
                return ResourceManager.GetString("LL075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminando inconsistencias de usuarios....
        /// </summary>
        internal static string LL076 {
            get {
                return ResourceManager.GetString("LL076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron centros de costos para el cliente seleccionado..
        /// </summary>
        internal static string LL077 {
            get {
                return ResourceManager.GetString("LL077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base de datos no disponible..
        /// </summary>
        internal static string LL078 {
            get {
                return ResourceManager.GetString("LL078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al generar el Reporte..
        /// </summary>
        internal static string LL079 {
            get {
                return ResourceManager.GetString("LL079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parametros de entrada no válidos..
        /// </summary>
        internal static string LL080 {
            get {
                return ResourceManager.GetString("LL080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se subio correctamente toda la información en la tabla de {0}. Archivo: {1} - BD: {2}..
        /// </summary>
        internal static string LL081 {
            get {
                return ResourceManager.GetString("LL081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en alguno de los e-mail en el campo &quot;{0}&quot;..
        /// </summary>
        internal static string LL082 {
            get {
                return ResourceManager.GetString("LL082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al procesar el registro del Empleado {0} con ID: {1}..
        /// </summary>
        internal static string LL083 {
            get {
                return ResourceManager.GetString("LL083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comienza proceso de generación de archivos: {0} {1}..
        /// </summary>
        internal static string LL084 {
            get {
                return ResourceManager.GetString("LL084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha finalizado el proceso de generación de archivos: {0} {1}..
        /// </summary>
        internal static string LL085 {
            get {
                return ResourceManager.GetString("LL085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo Registro en Base de datos de Empleado: {0}..
        /// </summary>
        internal static string LL086 {
            get {
                return ResourceManager.GetString("LL086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generando archivo de [iCodCatalogoEmple]: {0}  [Nombre]: {1}..
        /// </summary>
        internal static string LL087 {
            get {
                return ResourceManager.GetString("LL087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La nómina no existe: {0}..
        /// </summary>
        internal static string LL088 {
            get {
                return ResourceManager.GetString("LL088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró la extensión: {0}.
        /// </summary>
        internal static string LL089 {
            get {
                return ResourceManager.GetString("LL089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El empleado se encuentra actualmente en el centro de costos especificado..
        /// </summary>
        internal static string LL090 {
            get {
                return ResourceManager.GetString("LL090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible crear o identificar el puesto del empleado..
        /// </summary>
        internal static string LL091 {
            get {
                return ResourceManager.GetString("LL091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible actualizar la totalidad de los datos..
        /// </summary>
        internal static string LL092 {
            get {
                return ResourceManager.GetString("LL092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el empleado para crear la relación con la linea..
        /// </summary>
        internal static string LL093 {
            get {
                return ResourceManager.GetString("LL093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en alguno de los datos Opcionales del registro..
        /// </summary>
        internal static string LL094 {
            get {
                return ResourceManager.GetString("LL094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró la linea: {0}.
        /// </summary>
        internal static string LL095 {
            get {
                return ResourceManager.GetString("LL095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se permiten movimientos sobre el empleado &quot;POR IDENTIFICAR&quot; desde actualizaciones masivas..
        /// </summary>
        internal static string LL096 {
            get {
                return ResourceManager.GetString("LL096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta maestra no se encuentra activa para el carrier especificado o no existe..
        /// </summary>
        internal static string LL097 {
            get {
                return ResourceManager.GetString("LL097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Tipo de Empleado especificado en la nómina: {0} no es valido..
        /// </summary>
        internal static string LL098 {
            get {
                return ResourceManager.GetString("LL098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dato en el campo Organización para la nómina: {0} no es valido..
        /// </summary>
        internal static string LL099 {
            get {
                return ResourceManager.GetString("LL099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Por lo menos debe haber una columna declarada como clave cargo para poder cargar valores a la base.].
        /// </summary>
        internal static string LL100 {
            get {
                return ResourceManager.GetString("LL100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [ERROR al mapear datos de columnas fijas (ELIMINAR CARGA) : Reviar el contenido de las columnas: Reg. {0}].
        /// </summary>
        internal static string LL101 {
            get {
                return ResourceManager.GetString("LL101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Mensaje solamente informativo: El plan tarifario configurado en la linea {0} no corresponde a: {1}.].
        /// </summary>
        internal static string LL102 {
            get {
                return ResourceManager.GetString("LL102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Mensaje solamente informativo: El plan tarifario [{0}] no existe en Keytia.].
        /// </summary>
        internal static string LL103 {
            get {
                return ResourceManager.GetString("LL103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [ADVERTENCIA: La línea {0} no existe activa y relacionada en el rango de vigencia de la fecha de publicación de la factura, o tiene mas de una relacion en el periodo. No se sube información de esta línea.].
        /// </summary>
        internal static string LL104 {
            get {
                return ResourceManager.GetString("LL104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR: La línea {0} no existe activa y relacionada en el rango de vigencia de la fecha de publicación de la factura, o tiene mas de una relacion en el periodo.].
        /// </summary>
        internal static string LL105 {
            get {
                return ResourceManager.GetString("LL105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Por lo menos debe haber una columna declarada como clave cargo para poder cargar valores a la base.].
        /// </summary>
        internal static string LL106 {
            get {
                return ResourceManager.GetString("LL106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La columna: {0} no se encuentra en el archivo de detalle.].
        /// </summary>
        internal static string LL107 {
            get {
                return ResourceManager.GetString("LL107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Los renglones de encabezado no coinciden con los esperados.].
        /// </summary>
        internal static string LL108 {
            get {
                return ResourceManager.GetString("LL108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ErrInesp.
        /// </summary>
        internal static string LL109 {
            get {
                return ResourceManager.GetString("LL109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ErrGetSitioConf.
        /// </summary>
        internal static string LL110 {
            get {
                return ResourceManager.GetString("LL110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ------------------- Registros Nuevos en Factura: {0}.
        /// </summary>
        internal static string M001 {
            get {
                return ResourceManager.GetString("M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta: {0} - {1} [{2}], Subcuenta: {3}.
        /// </summary>
        internal static string M002 {
            get {
                return ResourceManager.GetString("M002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ------------------- Registros Baja en Factura: {0}.
        /// </summary>
        internal static string M003 {
            get {
                return ResourceManager.GetString("M003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baja: {0} - {1} [{2}], Subcuenta: {3}.
        /// </summary>
        internal static string M004 {
            get {
                return ResourceManager.GetString("M004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ------------------- Registros con cambio de Estatus en Factura: {0}.
        /// </summary>
        internal static string M005 {
            get {
                return ResourceManager.GetString("M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UpDate Baja a Alta:  {0} - {1} [{2}], Subcuenta: {3}.
        /// </summary>
        internal static string M006 {
            get {
                return ResourceManager.GetString("M006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ------------------- Registros con cambio de Cuenta Maestra en Factura: {0}.
        /// </summary>
        internal static string M007 {
            get {
                return ResourceManager.GetString("M007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UpDate de Cuenta - Subcuenta:  {0} - {1}.
        /// </summary>
        internal static string M008 {
            get {
                return ResourceManager.GetString("M008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número privado.
        /// </summary>
        internal static string NumeroPrivado {
            get {
                return ResourceManager.GetString("NumeroPrivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La suma de los totales no cuadra, por lo tanto no se sube información a BD. Total Detalles: {0}, Total Facturado: {1}].
        /// </summary>
        internal static string TIM0001 {
            get {
                return ResourceManager.GetString("TIM0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [No se especifico la cuenta maestra de la factura en la configuración de la carga.].
        /// </summary>
        internal static string TIM0002 {
            get {
                return ResourceManager.GetString("TIM0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Ya hay información en base de datos para las fechas y cuenta maestra que se esta seleccionando.].
        /// </summary>
        internal static string TIM0003 {
            get {
                return ResourceManager.GetString("TIM0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La carga no cuenta todos los archivos necesarios.].
        /// </summary>
        internal static string TIM0004 {
            get {
                return ResourceManager.GetString("TIM0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [El nombre de los archivos no cuenta con la estructura esperada.].
        /// </summary>
        internal static string TIM0005 {
            get {
                return ResourceManager.GetString("TIM0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La cuenta maestra especificada no existe o no es la misma en los nombres de los archivos.].
        /// </summary>
        internal static string TIM0006 {
            get {
                return ResourceManager.GetString("TIM0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La fecha de la factura no tiene el formato correcto.].
        /// </summary>
        internal static string TIM0007 {
            get {
                return ResourceManager.GetString("TIM0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Los nombres de los archivos deben contener la misma información en cuanto a cuenta maestra y fecha factura.].
        /// </summary>
        internal static string TIM0008 {
            get {
                return ResourceManager.GetString("TIM0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Error en la cantidad o nombre de los archivos con respecto a lo configurado en la carga].
        /// </summary>
        internal static string TIM0009 {
            get {
                return ResourceManager.GetString("TIM0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Error inesperado en la lectura y vaciado de la información del archivo: {0}].
        /// </summary>
        internal static string TIM0010 {
            get {
                return ResourceManager.GetString("TIM0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La clave cargo: &quot;{0}&quot; existe más de una vez en la Base de datos como clave TIM. Solo puede existir una con la misma descripción.].
        /// </summary>
        internal static string TIM0011 {
            get {
                return ResourceManager.GetString("TIM0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La clave cargo: &quot;{0}&quot; no existe en Base de datos, tiene encendida la bandera &quot;Baja para consolidado o no tiene un Tipo Destino definido.].
        /// </summary>
        internal static string TIM0012 {
            get {
                return ResourceManager.GetString("TIM0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Se encontró información de la cuenta: {0}].
        /// </summary>
        internal static string TIM0013 {
            get {
                return ResourceManager.GetString("TIM0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La fecha de corte de la factura no coincide con el DetalleFactura: Se encontró información de fecha de corte de: {0}].
        /// </summary>
        internal static string TIM0014 {
            get {
                return ResourceManager.GetString("TIM0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [El sitio: &quot;{0}&quot; existe más de una vez en la base de datos. Solo puede existir uno con la misma descripción.].
        /// </summary>
        internal static string TIM0015 {
            get {
                return ResourceManager.GetString("TIM0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Creación de SitioTIM: {0}, Error: {1}].
        /// </summary>
        internal static string TIM0016 {
            get {
                return ResourceManager.GetString("TIM0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Nuevo SitioTIM: {0}].
        /// </summary>
        internal static string TIM0017 {
            get {
                return ResourceManager.GetString("TIM0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La Clave cargo &quot;{0}&quot; no tiene un Tipo Destino especificado.].
        /// </summary>
        internal static string TIM0018 {
            get {
                return ResourceManager.GetString("TIM0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La Cuenta Maestra &quot;{0}&quot; no esta dada de alta en la base de datos.].
        /// </summary>
        internal static string TIM0019 {
            get {
                return ResourceManager.GetString("TIM0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [El Concepto: {0} que se esta cobrando en la factura no existe como Clave Cargo].
        /// </summary>
        internal static string TIM0020 {
            get {
                return ResourceManager.GetString("TIM0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Error al generar inventario : {0} ].
        /// </summary>
        internal static string TIM0021 {
            get {
                return ResourceManager.GetString("TIM0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Ya hay información en base de datos para la fecha seleccionada.].
        /// </summary>
        internal static string TIM0022 {
            get {
                return ResourceManager.GetString("TIM0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Error al vaciar los datos. En el registro: {0}].
        /// </summary>
        internal static string TIM0023 {
            get {
                return ResourceManager.GetString("TIM0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Error en Carga. Carga no Identificada.].
        /// </summary>
        internal static string TIM0024 {
            get {
                return ResourceManager.GetString("TIM0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [El Sitio: &quot;{0}&quot; no existe en la Base de datos.].
        /// </summary>
        internal static string TIM0025 {
            get {
                return ResourceManager.GetString("TIM0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [No se especifico el carruer de la factura en la configuración de la carga.].
        /// </summary>
        internal static string TIM0026 {
            get {
                return ResourceManager.GetString("TIM0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [El nombre de los archivos no cuenta con la estructura esperada. Ej: ClaveCarrier_NúmeroDeCuenta_FacturaXML_201601.xml ].
        /// </summary>
        internal static string TIM0027 {
            get {
                return ResourceManager.GetString("TIM0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La cuenta maestra especificada no existe o no pertenece al carrier especificado.].
        /// </summary>
        internal static string TIM0028 {
            get {
                return ResourceManager.GetString("TIM0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [El mes y año configurados en la carga son diferentes al mes y año en el nombre del archivo.].
        /// </summary>
        internal static string TIM0029 {
            get {
                return ResourceManager.GetString("TIM0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Error al insertar en la base de datos.].
        /// </summary>
        internal static string TIM0030 {
            get {
                return ResourceManager.GetString("TIM0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [El proceso actual no soporta el carrier configurado.].
        /// </summary>
        internal static string TIM0031 {
            get {
                return ResourceManager.GetString("TIM0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [La clave cargo: {0} existe en Base de datos pero no existe en los archivos. Encender la bandera &quot;Baja para consolidado&quot;.].
        /// </summary>
        internal static string TIM0032 {
            get {
                return ResourceManager.GetString("TIM0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [No se encontro fecha corte de la factura correspondiente al actual detalle.].
        /// </summary>
        internal static string TIM0033 {
            get {
                return ResourceManager.GetString("TIM0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [No se encontro un tipo de cambio para la moneda Global en las en las fechas de la factura.].
        /// </summary>
        internal static string TIM0034 {
            get {
                return ResourceManager.GetString("TIM0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Ocurrio un error al momento de generar el inventario de enlaces.].
        /// </summary>
        internal static string TIM0035 {
            get {
                return ResourceManager.GetString("TIM0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Los Siguientes importes no tienen una equivalencia en el Historico de RelacionImporte {0}].
        /// </summary>
        internal static string TIM0036 {
            get {
                return ResourceManager.GetString("TIM0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [El registro con CuentaServicio: {0}, Sitio: {1} y Carrier: {2} no corresponde al catalogo de Cuentas de Servicio ].
        /// </summary>
        internal static string TIM0037 {
            get {
                return ResourceManager.GetString("TIM0037", resourceCulture);
            }
        }
    }
}
